```{r}
library(twitteR)
library(lubridate)
library(ggplot2)
library(tm)
library(tidytext)
library(qdap)
library(stringr)
library(SnowballC)
library(RWeka)
library(wordcloud)
library(dplyr)
library(dendextend)
library(topicmodels)
library(ggthemes)
library(shiny)
library(shinyWidgets)
library(shinythemes)
library(DT)
library(RColorBrewer)
library(shinydashboard)
library(plotly)

`%notin%` <- Negate(`%in%`)

afinn <- read.csv("dicc sent/afinn_español.csv", stringsAsFactors = F, fileEncoding = "latin1") %>%
  tbl_df()
```


```{r}
setup_twitter_oauth(consumer_key = "u2UthjbK6YHyQSp4sPk6yjsuV",
  consumer_secret = "sC4mjd2WME5nH1FoWeSTuSy7JCP5DHjNtTYU1X6BwQ1vPZ0j3v",
  access_token = "1365606414-7vPfPxStYNq6kWEATQlT8HZBd4G83BBcX4VoS9T",
  access_secret = "0hJq9KYC3eBRuZzJqSacmtJ4PNJ7tNLkGrQrVl00JHirs")
```


```{r}
descarga <- function(tema, numero){
  tweets <- searchTwitter(tema, lang = "es", n = numero,retryOnRateLimit = 100)
  tw = tweet_df(tweets)
  return(tw)
}

tweet_df <- function(tweets){
  total = length(tweets)
  
  id = character(total)
  date = character(total)
  text = character(total)
  retweets = integer(total)
  author = character(total)
  
  for (t in 1:length(tweets)){
    id[t] <- tweets[[t]]$id
    date[t] <- as.character(tweets[[t]]$created)
    text[t] <- tweets[[t]]$text
    retweets[t] <- tweets[[t]]$retweetCount
    author[t] <- tweets[[t]]$screenName
  }

  tw <- data.frame(
    doc_id = id,
    text = text,
    date = ymd_hms(date),
    author = author,
    retweets = retweets
  )
  return(tw)
}
```

```{r}
qdap_clean = function(x){
  x=replace_abbreviation(x)
  x=replace_contraction(x)
  x=replace_number(x, remove = T)
  x=replace_ordinal(x)
  x=replace_symbol(x)
  x=tolower(x)
  x=str_replace_all(x, "á", "a")
  x=str_replace_all(x, "é", "e")
  x=str_replace_all(x, "í", "i")
  x=str_replace_all(x, "ó", "o")
  x=str_replace_all(x, "ú", "u")
  #x=str_remove_all(x, pattern = "[!¿¡?]|[…]|[“•»«]")
  #x=x[-grep(x, pattern = "^[^a-zA-Záéíóúñ]+$")]
  x=str_remove_all(x, pattern = "[^a-zA-ZÁÉÍÓÚñ ]+")
  #x=x[-grep(rownames(tweet_tdm_m), pattern = "https")]
  x=str_remove_all(x, pattern = " ?https.* ?")
  return(x)
}

tm_clean=function(corpus, stopwords){
  corpus = tm_map(corpus, removePunctuation)
  corpus = tm_map(corpus, stripWhitespace)
  corpus = tm_map(corpus, removeWords,
                  stopwords)
  return(corpus)
}

corpus_creator <- function(df, stopwords){
  corp <- tm_clean(VCorpus(DataframeSource(df)), stopwords)
  return(corp)
}

tokenizer <- function(x){
  NGramTokenizer(x, Weka_control(min=1, max=2))
}

tdm_creator <- function(corp){
  tdm <- TermDocumentMatrix(corp,
                     control=list(tokenize = tokenizer))
  return(tdm)
}

tfidf_creator <- function(corp){
  tfidf <- TermDocumentMatrix(corp,
                     control = list(weighting = weightTfIdf,
                        tokenize = tokenizer))
  return(tfidf)
}

tidy_words_creator <- function(df, stopwords){
  tidy <- df %>% 
    unnest_tokens(output = "word", token = "words", input = text) %>% 
    filter(word %notin% stopwords) %>% 
    #mutate(word = wordStem(word))
  return(tidy)
}

limpiar <- function(df, stop_aux = NULL){
  stop_words_my <- c(stop_aux, tm::stopwords("es"), "number", "rt", "at", "eramos", "d", "cada",
                     "mas", "s", "aqui", "ref", "asi", "solo", "hacia", "aas", "aavv", "araya")
  
  df$text <- qdap_clean(df$text)
  tweet_corp <- corpus_creator(df, stop_words_my)
  tweet_tdm <- tdm_creator(tweet_corp)
  tweet_tfidf <- tfidf_creator(tweet_corp)
  tweet_tdm_m <- as.matrix(tweet_tdm)
  tweet_tfidf_m <- as.matrix(tweet_tfidf)
  tweet_tidy <- tidy_words_creator(df, stop_words_my)
  tweet_tfidf_freq <- rowSums(tweet_tfidf_m)
  tweet_tdm_freq <- rowSums(tweet_tdm_m)
  
  resultado <- list(tweet_tdm,
                    tweet_tfidf, 
                    tweet_tdm_m,
                    tweet_tfidf_m,
                    tweet_tdm_freq,
                    tweet_tfidf_freq,
                    tweet_tidy,
                    tweet_corp)
  return(resultado)
}
```

```{r}
dendograma <- function(tdm, dispersion, palabras_coloreadas = NULL, color = "red"){
  hc <- hclust(dist(removeSparseTerms(tdm, sparse = dispersion)))
  hcd <- as.dendrogram(hc)
  if (!is.null(palabras_coloreadas)){
    hcd <- branches_attr_by_labels(hcd, palabras_coloreadas, color)
  }
  plot(hcd, main = "Dendograma")
}
```

```{r}
crear_lda <- function(corpus, ntopic){
  tweet_dtm <- DocumentTermMatrix(corpus)
  tweet_dtm <- tweet_dtm[which(rowSums(as.matrix(tweet_dtm))>0),]
  tweet_lda <- LDA(tweet_dtm, k = ntopic, method = 'Gibbs')
  return(tweet_lda)
}

crear_topicos <- function(lda, ntopics){
  topic_list <- vector(mode = "list", length = (ntopics + 1))
  
  lda_beta <- lda %>% tidy(matrix = "beta")
  lda_gamma <- lda %>% tidy(matrix = "gamma")
  
  lda_gamma_ordered <- lda_gamma %>% 
  group_by(document)%>%  
  arrange(desc(gamma))%>%  
  slice(1)%>%  
  group_by(topic)%>%  
  tally(topic, sort=TRUE)
  
  topic_list[[1]] <- lda_gamma_ordered
  
  for (tpc in 1:ntopics){
    topic_words <- lda_beta %>% 
      filter(topic == tpc) %>% 
      top_n(10, beta) %>% 
      arrange(desc(beta))
    topic_list[[tpc + 1]] <- topic_words
  }
  return(topic_list)
}

topicos <- function(corpus, ntopic){
  lda <- crear_lda(corpus, ntopic)
  topicos <- crear_topicos(lda, ntopic)
  return(topicos)
}
```

```{r}
afinn_df <- function(df, remove_outliers, hater){
  tweet_sent <- 
    df %>% 
    inner_join(afinn, by = c("word" = "Palabra")) %>% 
    group_by(doc_id, date, author, retweets) %>% 
    summarise(suma = sum(Puntuacion)) %>% 
    ungroup() %>% 
    mutate(hater = ifelse(suma<=hater, TRUE, FALSE))
  if (remove_outliers){
    tweet_sent <- tweet_sent %>% filter(retweets <= mean(retweets)+3*sd(retweets))
  }
  return(tweet_sent)
}

my_theme <- function(){
  theme_minimal() + 
    theme(
      panel.grid.major.y=element_line(linetype = "dashed", color = "grey80"),
      panel.grid.major.x=element_line(linetype = "dashed", color = "grey80"),
      panel.grid = element_blank(), 
      panel.background = element_blank(),
      axis.ticks.y = element_blank(),
    )
}
```












```{r}
ui <- fluidPage(
  theme = shinythemes::shinytheme("spacelab"),
  sidebarLayout(
    sidebarPanel(
      textInput(
      inputId = "hastag",
      label = "Escribe el hastag que quieras buscar", 
      placeholder = "#Hastag",
      width = "100%"
        ),
      sliderTextInput(
      inputId = "numtweets",
      label = "Elige cantidad de tweets:", 
      choices = c(200, 500, 1000, 5000, 10000, 20000, 50000),
      grid = TRUE
        ),
      actionButton(
        "button", "Aprietame para continuar"
        ),
      hr(),
      textInput("stopwords",
        label = "Eliminar palabra(s)",
        placeholder = 'Separalas por ", " Ejemplo: a, ante, bajo, con...'
        ),
      switchInput(
        inputId = "dividir_palabras",
        label = "Eliminar", 
        value = F,
        onStatus = "success",
        offStatus  = "success",
        onLabel = "Presioname",
        offLabel = "Presioname"
        )
      ),
    mainPanel(
      tabsetPanel(
        tabPanel("Tabla", DT::DTOutput("tweets_tabla")),
        tabPanel("Word Cloud", plotOutput("wordcloud"),
                               sliderTextInput(
                                 inputId = "max_pal_word",
                                 label = "Maximo de palabras", 
                                 choices = 1:150,
                                 selected = 30,
                                 from_min = 20,
                                 from_max = 120
                                )),
        tabPanel("Dendograma", plotOutput("dend"),
                               sliderTextInput(
                                 inputId = "dispersion",
                                 label = "Dispersion de las palabras",
                                 choices = seq(from = 0.93, to = 0.99, by = 0.005)),
                               textInput("coloreadas",
                                 label = "Marca las palabras importantes",
                                 placeholder = 'Separalas por ", " Ejemplo: a, ante, bajo, con...'),
                               pickerInput(
                                 inputId = "select_color",
                                 label = "Selecciona Color", 
                                 choices = c("red", "blue", "green", "yellow", "pink", "purple"),
                                 choicesOpt = list(
                                 style = c("color: white; background: red;", 
                                           "color: white; background: blue",
                                           "color: white; background: green",
                                           "color: white; background: yellow",
                                           "color: white; background: pink",
                                           "color: white; background: purple"
                                           )))),
        tabPanel("Topicos", DT::DTOutput("topico"),
                            sliderTextInput(
                              inputId = "numerotopicos",
                              label = "Numero de topicos",
                              choices = 1:14,
                              selected = 3),
                            awesomeRadio(
                              inputId = "topicoelegido",
                              label = "Radio buttons", 
                              choices = 0:14,
                              selected = 0,
                              inline = TRUE, 
                              checkbox = TRUE)),
        tabPanel("Graficos",
                 sidebarLayout(
                   sidebarPanel(
                     prettyToggle(
                     inputId = "outliers",
                     label_on = "Outliers eliminados", 
                     label_off = "Outliers integrados!!!",
                     inline=T
                       ),
                     sliderTextInput(
                       inputId = "hater",
                       label = "Puntuacion hater",
                       choices = -10:10,
                       from_min = -10,
                       from_max = 0,
                       selected = -3
                     )
                   ),
                   mainPanel(
                     tabsetPanel(
                       tabPanel("Retweets", plotly::plotlyOutput("count")),
                       tabPanel("Histograma", plotly::plotlyOutput("histograma")),
                       tabPanel("Haters", DT::DTOutput("hatertext"))
                       ),
                     textOutput("porcentaje"),
                     )
                   )
                 )
      )
    )
  )
)

server <- function(input, output, session){
  rval_button <- eventReactive(input$button, {
    hast <- input$hastag
    if (!grepl(hast, pattern = "^#")){
      hast = str_glue("#", hast)
    }
    tweet_dataframe <- descarga(hast, input$numtweets)
    return(tweet_dataframe)
  })
  output$tweets_tabla <- DT::renderDT({
    hastag_numero <- rval_button()
  })
  rval_stopwords <- eventReactive(input$dividir_palabras, {
    stopwords_adicionales_sucio <- input$stopwords
    stopwords_adicionales <- str_split(stopwords_adicionales_sucio, pattern=", ", simplify = T)
    return(stopwords_adicionales)
  })
  rval_recursos <- reactive({
    tweet_df <- rval_button()
    stopwords_adicionales <- rval_stopwords()
    recursos <- limpiar(tweet_df, stopwords_adicionales)
    return(recursos)
  })
  output$wordcloud <- renderPlot({
    freq_matrix <- rval_recursos()[[5]]
    wordcloud(
      words = names(freq_matrix),
      freq = freq_matrix,
      scale=c(4,0.5),
      max.words=input$max_pal_word,
      colors=brewer.pal(8, "Dark2")
    )
  })
  output$dend <- renderPlot({
    tdm_tweet <- rval_recursos()[[1]]
    palabras_color_sucio <- input$coloreadas
    palabras_color <- str_split(palabras_color_sucio, pattern=", ", simplify = T)
    dendograma(tdm_tweet, input$dispersion, palabras_color, input$select_color)
  })
  rval_topico <- reactive({
    lista_tpc <- topicos(rval_recursos()[[8]], input$numerotopicos)
  })
  output$topico <- DT::renderDT({
    mostrar<-rval_topico()[[as.numeric(input$topicoelegido) + 1]] 
  })
  rval_sentimiento <- reactive({
    df_sent <- afinn_df(rval_recursos()[[7]],
                        remove_outliers = input$outliers,
                        hater = input$hater)
  })
  output$count <- plotly::renderPlotly({
    ggplot(rval_sentimiento(), aes(suma, retweets, color = hater))+
      geom_count()+
      labs(size = "Cantidad retweets")+
      my_theme()
  })
  rval_altura_hate <- reactive({
    alt_hate = rval_sentimiento() %>% count(suma) %>% summarise(sum(n)/8) %>% pull()
  })
  output$histograma <- plotly::renderPlotly({
    ggplot(rval_sentimiento(), aes(suma, color=hater, fill = hater))+
      geom_histogram(binwidth = 1)+
      labs(x = "Número de Tweets",
           y = "Valoracion de los tweets",
           title = "Cantidad de tweets por valoracion")+
      geom_vline(xintercept = input$hater + 0.5, color= "red", linetype="longdash")+
      geom_text(aes(x = input$hater - 0.4,
                    y = rval_altura_hate(),
                    label="Haters",
                    angle=90), color="red")+
      my_theme()+
      theme(legend.position = "none")+
      scale_fill_manual(values=c("#56B4E9", "firebrick1"))
  })
  output$porcentaje <- renderText(
    paste("El porcentaje de haters es de", sum(rval_sentimiento()$hater) / nrow(rval_sentimiento()))
  )
  output$hatertext <- DT::renderDT(
    rval_sentimiento() %>%
      filter(hater) %>% 
      inner_join(rval_button(), by = c("doc_id", "date", "author", "retweets")) %>%
      arrange(suma) %>% 
      select(doc_id, text, everything())
  )
}

shinyApp(ui, server)
```

```{r}
shinyWidgetsGallery()
```

